sudo: false
language: node_js
node_js:
  - stable
  - '10'
  - '8'
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^release\/.*$/
notifications:
  email:
    on_success: never
cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - 'commitlint-travis'
  - 'yarn linter'
script: 'yarn test --logHeapUsage'
after_script: 'yarn coverage'
