sudo: false
language: node_js
node_js:
- stable
- '8'
- '6'
- '4'
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^greenkeeper-.*$/
    - /^greenkeeper/.*$/
notifications:
  email:
    on_success: never
cache:
  directories:
  - node_modules

before_script:
  - 'commitlint-travis'
  - 'yarn linter'
script: 'yarn test'
after_script: 'yarn coverage'
