sudo: false
language: node_js
node_js:
  - 'stable'
  - '10'
matrix:
  fast_finish: true
branches:
  only:
    - master
    - /^release\/.*$/
notifications:
  email:
    on_success: never
cache:
  directories:
    - 'node_modules'

before_script: 'yarn linter'
script: 'yarn test'
after_script: 'yarn coverage'
