name: Build and Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16']
    name: Test using node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn test --forbid-only
      - uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  integration:
    runs-on: ubuntu-latest
    name: Integration tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn cypress:run --record --key ${{secrets.CYPRESS_KEY}}
        env:
          CI: true
          COMMIT_INFO_BRANCH: ${GITHUB_REF}

  linter:
    runs-on: ubuntu-latest
    name: Linter
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install
      - run: yarn linter
