
name: Ship js Manual Prepare
on:
  issue_comment:
    types: [created]
jobs:
  manual_prepare:
    if: |
      github.event_name == 'issue_comment' &&
      (github.event.comment.author_association == 'member' || github.event.comment.author_association == 'owner') &&
      startsWith(github.event.comment.body, '@shipjs prepare')
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-node@master
      - run: |
          if [ -f "yarn.lock" ]; then
            yarn install
          else
            npm install
          fi
      - run: |
          git config --global user.email "mail@markus-wolf.de"
          git config --global user.name "Markus Wolf"
      - run: npm run release:prepare -- --yes --no-browse
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  create_done_comment:
    if: success()
    needs: manual_prepare
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/github@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "@${{ github.actor }} `shipjs prepare` done"

  create_fail_comment:
    if: cancelled() || failure()
    needs: manual_prepare
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/github@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "@${{ github.actor }} `shipjs prepare` fail"
    
