name: Website
on:
  release:
    types:
      - 'released'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Create website version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 12
      - name: run
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm install -g yarn
          cd website
          yarn install
          yarn run version ${GITHUB_REF#refs/tags/v}
          git add --all
          git commit -m "docs: create new website version"
          git push origin master
