name: Website
on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/**'
      - 'website/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build + Deploy Website
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: run
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm install -g yarn
          cd website
          yarn install
          yarn build
          yarn publish-gh-pages
